[package]
name = "google-docs-but-its-your-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "*"
tui-textarea = { version = "*", features = ["search"] }
